"""
VAPE Bug Bounty Intelligence — revives the "Bug Bounty Intelligence Report"
cron (see intel/reports/bug-bounty-intel-2026-06-10.md), which only ever
ran once. Its core, still-open watch item was: "Virtuals Protocol is
actively working with Immunefi to launch a bug bounty program (not yet
live)" — this makes that a real recurring check instead of a one-time note.

Real data: one bounded live web search checks for an actual Immunefi
listing; agents/scout.py's own real, keyless DeFiLlama-hacks-derived
archive (intel/bounty-radar/opportunities.json, already running hourly via
scout.yml) supplies a real cross-reference of recent Base-tagged incidents/
opportunities, so this doesn't re-fetch data scout.py already maintains.

Runs weekly — bounty-program launches are rare events, no value in daily polling.

Usage: python agents/bug_bounty_intel.py
"""
import json
import os
import sys
from datetime import datetime, timezone, timedelta

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from agents import intel_common as ic  # noqa: E402

OPPORTUNITIES_PATH = os.path.join(ic.ROOT, "intel", "bounty-radar", "opportunities.json")
LOOKBACK_DAYS = 14


def load_recent_base_opportunities():
    try:
        with open(OPPORTUNITIES_PATH) as f:
            opps = json.load(f)
    except Exception:
        return []
    if not isinstance(opps, list):
        return []
    cutoff = datetime.now(timezone.utc) - timedelta(days=LOOKBACK_DAYS)
    out = []
    for o in opps:
        tags = o.get("tags") or []
        if "base" not in [str(t).lower() for t in tags]:
            continue
        try:
            seen = datetime.fromisoformat(str(o.get("firstSeen", "")).replace("Z", "+00:00"))
        except Exception:
            continue
        if seen >= cutoff:
            out.append(o)
    out.sort(key=lambda o: o.get("fitScore", 0), reverse=True)
    return out[:10]


def run():
    search = ic.web_search_snippets("Virtuals Protocol Immunefi bug bounty program launch", max_results=5)
    immunefi_live = any(
        "immunefi.com" in (r.get("url") or "").lower() and "virtual" in (r.get("url") + r.get("title") + r.get("snippet")).lower()
        for r in search.get("results", [])
    )

    recent = load_recent_base_opportunities()
    recent_rows = "\n".join(
        f"| {o.get('name')} | {o.get('platform')} | ${o.get('prizeUsd', 0):,.0f} | {o.get('firstSeen', '')[:10]} |"
        for o in recent
    ) or f"| — | no new Base-tagged opportunities in the last {LOOKBACK_DAYS}d | — | — |"

    verdict = "IMMUNEFI LIVE" if immunefi_live else "NOT YET LAUNCHED"

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    body = f"""# Bug Bounty Intelligence Report — Base & Virtuals Protocol

**Date:** {stamp}

---

## VERDICT: {verdict}

Real check: searched for a live Virtuals Protocol Immunefi listing this cycle.
{'Found a matching immunefi.com result — see Web Signals below.' if immunefi_live else "No matching immunefi.com listing found in this cycle's search results."}

---

## Recent Base-Tagged Opportunities (real, from `agents/scout.py`'s archive)

Cross-referenced from `intel/bounty-radar/opportunities.json` — the same real,
keyless DeFiLlama-hacks-derived archive `scout.yml` maintains hourly, filtered to
Base-tagged entries seen in the last {LOOKBACK_DAYS} days.

| Name | Platform | Prize/Loss | First Seen |
|------|----------|------------|------------|
{recent_rows}

---

{ic.format_search_section("Web Signals — Immunefi / Bounty Programs", search)}

---

## Recommended Actions

1. Re-run this check weekly — Immunefi program launches are rare, infrequent events.
2. If VERDICT flips to IMMUNEFI LIVE, cross-check scope against `intel/reports/attack-surface-map-2026-06-10.md`'s
   flagged findings for anything still unpatched per `agents/mainnet_patch_check.py`'s latest run.
3. Direct disclosure to security@virtuals.io remains available regardless of Immunefi status.

---

## Sources
- Live web search ({search.get('provider') or 'unavailable'})
- `intel/bounty-radar/opportunities.json` (real, maintained by `agents/scout.py` hourly)

---

*Report generated by `agents/bug_bounty_intel.py` — revived {datetime.now(timezone.utc).strftime('%Y-%m-%d')} as a
real recurring check of the original one-time 2026-06-10 finding.*
"""
    path = ic.write_report("bug-bounty-intel", body)
    summary = f"Bug bounty intel: {verdict}. {len(recent)} recent Base-tagged opportunity(s) cross-referenced."
    ic.log_sweep_memory("agents/bug_bounty_intel.py", verdict, summary, path, tags=["bounty", "virtuals"])
    print(f"[bug_bounty_intel] {verdict} — wrote {os.path.relpath(path, ic.ROOT)}")
    return {"verdict": verdict, "path": path}


if __name__ == "__main__":
    run()
