"""
VAPE build-request agent — turns a labeled GitHub issue into a real,
reviewable PR. This is the concrete instantiation of "VAPE can build
tools/apps/anything needed": open an issue describing what you want built,
apply the `vape-build` label, and Builder (agents/builder.py's
generate_project()) attempts a real multi-file implementation grounded in
Memory and scoped to VAPE's actual specialization areas and tech stack.

Safety boundary, same principle as self_improve.py: generated files land in
an isolated build-requests/issue-<N>-<slug>/ directory via a PR, never
directly into existing production files — a human decides whether/how/where
to actually integrate it. Builder's own security validation (blocks
eval/exec/shell/unsafe deserialization) is the first gate; PR review is the
second. Labeling an issue is itself a maintainer action by default on
GitHub (not available to arbitrary external commenters), which is the gate
on who can trigger a build at all.

Triggered by .github/workflows/build-request.yml on the `issues: labeled`
event (real-time, not polled) — reads the issue number/title/body from
environment variables the workflow passes from the GitHub event payload
directly, since the workflow already has that data for free.
"""
import os
import re
import subprocess
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from agents.builder import Builder, validate_security  # noqa: E402

try:
    from skillforge.mcp import GitHubMCPWrapper  # noqa: E402
except Exception:
    GitHubMCPWrapper = None

try:
    from skillforge.memory.retriever import append_to_memory  # noqa: E402
except Exception:
    append_to_memory = None

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPORTS_DIR = os.path.join(_REPO_ROOT, "reports")
REPO_SLUG = "jUXTAPOSITION1/V.A.P.E"


def _run(cmd, **kwargs):
    return subprocess.run(cmd, cwd=_REPO_ROOT, capture_output=True, text=True, **kwargs)


def _git_current_branch():
    return _run(["git", "rev-parse", "--abbrev-ref", "HEAD"]).stdout.strip()


def _now_stamp():
    return datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")


def open_build_pr(issue_number, issue_title, files, warnings):
    if not os.getenv("GITHUB_TOKEN") or GitHubMCPWrapper is None:
        print("[BuildRequest] No GITHUB_TOKEN / MCP wrapper available — skipping PR, report-only.")
        return None

    original_branch = _git_current_branch()
    slug = re.sub(r"[^a-z0-9]+", "-", issue_title.lower()).strip("-")[:40]
    branch = f"vape-build-{issue_number}-{slug}-{_now_stamp()}"
    out_dir_rel = os.path.join("build-requests", f"issue-{issue_number}-{slug}")
    out_dir = os.path.join(_REPO_ROOT, out_dir_rel)

    try:
        os.makedirs(out_dir, exist_ok=True)
        for rel_path, content in files.items():
            full_path = os.path.join(out_dir, rel_path)
            os.makedirs(os.path.dirname(full_path), exist_ok=True)
            with open(full_path, "w", encoding="utf-8") as f:
                f.write(content)

        readme = (
            f"# VAPE build request — issue #{issue_number}\n\n"
            f"**Requested:** {issue_title}\n\n"
            f"**Security review:** {'clean' if not warnings else '; '.join(warnings)}\n\n"
            "This is a PROPOSAL, not applied automatically. A human reviews this PR and "
            "decides whether/how/where to integrate it into the real codebase.\n\n"
            "## Files\n" + "\n".join(f"- `{p}`" for p in files)
        )
        with open(os.path.join(out_dir, "README.md"), "w") as f:
            f.write(readme)

        _run(["git", "config", "user.name", "VAPE Bot"])
        _run(["git", "config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com"])
        _run(["git", "checkout", "-b", branch])
        _run(["git", "add", out_dir_rel])
        commit = _run(["git", "commit", "-m", f"VAPE build request: issue #{issue_number} — {issue_title}"])
        if commit.returncode != 0:
            print(f"[BuildRequest] Nothing to commit: {commit.stdout}{commit.stderr}")
            return None
        push = _run(["git", "push", "-u", "origin", branch])
        if push.returncode != 0:
            print(f"[BuildRequest] Push failed: {push.stderr}")
            return None

        gh = GitHubMCPWrapper()
        body = (
            f"Addresses #{issue_number}\n\n"
            f"**Security review:** {'clean' if not warnings else ', '.join(warnings)}\n\n"
            f"Generated by `agents/build_request.py` from the issue above. Files land under "
            f"`{out_dir_rel}/` for review — nothing was applied to the existing codebase "
            f"automatically.\n\n## Files\n" + "\n".join(f"- `{p}`" for p in files)
        )
        success, pr_data = gh.create_pr(
            repo=REPO_SLUG,
            title=f"VAPE build: {issue_title}"[:100],
            body=body,
            head=branch,
        )
        if success:
            print(f"[BuildRequest] PR opened: {pr_data.get('url')}")
            return pr_data.get("url")
        print(f"[BuildRequest] PR creation failed: {pr_data}")
        return None
    finally:
        _run(["git", "checkout", original_branch])


def _log_lesson(issue_number, issue_title, files, pr_url):
    if append_to_memory is None:
        return
    outcome = "opened a real PR" if pr_url else ("generated files but PR creation failed/skipped" if files else "generated nothing this cycle")
    try:
        append_to_memory(
            category="lesson",
            title=f"build_request: issue #{issue_number} — {issue_title[:80]} — {outcome}",
            content=f"Files: {list(files.keys())}\nOutcome: {outcome}" + (f"\nPR: {pr_url}" if pr_url else ""),
            source="agents/build_request.py",
            tags=["build-request", "builder"],
            confidence=0.75,
            metadata={"issue_number": issue_number, "pr_url": pr_url, "files": list(files.keys())},
        )
    except Exception as e:
        print(f"[BuildRequest] could not log lesson: {e}")


def main():
    issue_number = os.environ.get("ISSUE_NUMBER", "").strip()
    issue_title = os.environ.get("ISSUE_TITLE", "").strip()
    issue_body = os.environ.get("ISSUE_BODY", "").strip()

    os.makedirs(REPORTS_DIR, exist_ok=True)
    report_path = os.path.join(REPORTS_DIR, f"build_request_{_now_stamp()}.md")

    if not issue_number or not issue_title:
        with open(report_path, "w") as f:
            f.write("# VAPE Build Request — missing issue data\n\n"
                     "ISSUE_NUMBER/ISSUE_TITLE environment variables were not set — aborting "
                     "rather than fabricating a target.\n")
        print("[BuildRequest] missing issue number/title — aborting.")
        return

    builder = Builder()
    if not builder.llm_ready:
        with open(report_path, "w") as f:
            f.write(f"# VAPE Build Request — issue #{issue_number}\n\n"
                     "No LLM provider available this cycle — logging the request for a "
                     "future run instead of fabricating a build.\n")
        print("[BuildRequest] no LLM available — skipping.")
        return

    task = (
        f"GitHub issue #{issue_number}: {issue_title}\n\n{issue_body}\n\n"
        "This request came from a real GitHub issue on VAPE's own repository, labeled "
        "'vape-build' by a maintainer. Build exactly what's asked, scoped to VAPE's real "
        "stack and specialization areas — never invent scope beyond the issue text."
    )
    files, metadata = builder.generate_project(task=task, review=True, tier="deep")
    combined = "\n\n".join(files.values()) if files else ""
    _, warnings = validate_security(combined, task) if files else (True, [])

    pr_url = open_build_pr(issue_number, issue_title, files, warnings) if files else None
    _log_lesson(issue_number, issue_title, files, pr_url)

    report = (
        f"# VAPE Build Request — issue #{issue_number}: {issue_title}\n\n"
        "## Files generated\n"
        + ("\n".join(f"- `{p}`" for p in files) if files else "None — Builder produced no usable FILE blocks this cycle.")
        + "\n\n"
        + (f"PR opened: {pr_url}\n" if pr_url else "No PR opened (see log for why).\n")
    )
    with open(report_path, "w") as f:
        f.write(report)
    print(f"[BuildRequest] cycle complete. Report: {os.path.relpath(report_path, _REPO_ROOT)}")


if __name__ == "__main__":
    main()
