"""
VAPE Virtuals Protocol & ACP Sweep — revives the "Virtuals Protocol & ACP
Sweep Report" cron (see intel/reports/virtuals-*.md). Same story as
security_sweep.py's docstring.

Real data: agents/data_fetchers.get_virtuals_snapshot() (VIRTUAL price/mcap/
volume + protocol TVL, keyless CoinGecko+DefiLlama) for the ecosystem side,
and data/reputation.json (this repo's own real, published activity ledger —
generated by agents/publish_reputation.py from actual git/ACP history) for
VAPE's own agent status, instead of re-deriving it from a live ACP CLI call
each cycle. PROTOCOL HEALTH is computed deterministically from the real
VIRTUAL price trend. One bounded web search adds ecosystem news.

Usage: python agents/virtuals_sweep.py
"""
import json
import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from agents.data_fetchers import get_virtuals_snapshot  # noqa: E402
from agents import intel_common as ic  # noqa: E402
from agents import llm  # noqa: E402

REPUTATION_PATH = os.path.join(ic.ROOT, "data", "reputation.json")


def load_reputation():
    try:
        with open(REPUTATION_PATH) as f:
            return json.load(f)
    except Exception:
        return {}


def compute_health_score(snapshot):
    """0-10, starts neutral at 5. Real VIRTUAL 24h price change drives the
    swing — see intel_common.py's module docstring for why this isn't LLM-guessed."""
    score = 5.0
    chg = snapshot.get("virtual_change_24h_pct")
    if isinstance(chg, (int, float)):
        if chg >= 5:
            score += 2
        elif chg > 0:
            score += 1
        elif chg <= -10:
            score -= 2
        elif chg < 0:
            score -= 1
    return max(0, min(10, round(score, 1)))


def run():
    snapshot = get_virtuals_snapshot()
    rep = load_reputation()
    score = compute_health_score(snapshot)

    identity = rep.get("identity", {})
    activity = rep.get("verifiable_activity", {})
    offerings = rep.get("capabilities", {}).get("offerings", [])
    live_offerings = [o for o in offerings if o.get("auto") or o.get("x402")]

    search = ic.web_search_snippets("Virtuals Protocol ACP agent commerce news update", max_results=5)

    system = (
        "You are VAPE, an autonomous agent reporting on the Virtuals Protocol ecosystem it "
        "operates in. Write using ONLY the real numbers and search results provided — never "
        "invent ecosystem stats, agent counts, or news beyond what's given."
    )
    user = (
        f"PROTOCOL HEALTH (already computed, do not change it): {score}/10\n"
        f"VIRTUAL price: ${snapshot.get('virtual_price_usd', 'unavailable')} "
        f"({snapshot.get('virtual_change_24h_pct', 'unavailable')}% 24h)\n"
        f"VIRTUAL market cap: ${snapshot.get('virtual_mcap_usd', 'unavailable')}\n"
        f"Virtuals Protocol TVL: ${snapshot.get('protocol_tvl_usd', 'unavailable')}\n"
        f"VAPE's own real activity: {json.dumps(activity)}\n"
        f"VAPE's live offerings: {len(live_offerings)} of {len(offerings)} total\n\n"
        f"Web search on Virtuals/ACP news:\n"
        f"{[r['title'] + ': ' + r['snippet'] for r in search.get('results', [])] or 'none available'}\n\n"
        "Write two sections in markdown, each starting with '### ':\n"
        "1. Ecosystem & ACP Activity — what the price/TVL numbers and search results say "
        "about protocol health right now.\n"
        "2. Action Items for VAPE — 3-5 bullets grounded in VAPE's own real activity numbers above."
    )
    narrative, provider = llm.ask_safe(system, user, tier="deep", max_tokens=1200,
                                       provider_order=llm.FRONTIER_ORDER)

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    body = f"""# Virtuals Protocol & ACP Sweep Report

**Date:** {stamp}
**Agent:** VAPE (token `{identity.get('vape_token', 'unknown')}`, Base chain 8453)

---

## PROTOCOL HEALTH: {score}/10

Computed deterministically from VIRTUAL's real 24h price change ({snapshot.get('virtual_change_24h_pct', '—')}%).

---

## Token Movement — VIRTUAL (real, CoinGecko)

| Metric | Value |
|---|---|
| Price | {ic.fmt_price(snapshot.get('virtual_price_usd'))} |
| 24h Change | {snapshot.get('virtual_change_24h_pct') if snapshot.get('virtual_change_24h_pct') is not None else 'unavailable'}% |
| Market Cap | {ic.fmt_usd(snapshot.get('virtual_mcap_usd'))} |
| 24h Volume | {ic.fmt_usd(snapshot.get('virtual_vol_24h_usd'))} |
| Protocol TVL | {ic.fmt_usd(snapshot.get('protocol_tvl_usd'))} |

---

## VAPE's Own ACP Status (real, from `data/reputation.json`)

| Field | Value |
|---|---|
| Agent | {identity.get('name', 'VAPE')} |
| Wallet | {identity.get('wallet', '—')} |
| ERC-8004 ID | {identity.get('erc8004_id', '—')} |
| Live Offerings | {len(live_offerings)} of {len(offerings)} |
| Reports Published | {activity.get('reports_published', '—')} |
| Intel Reports | {activity.get('intel_reports', '—')} |
| Catalog Investigations | {activity.get('catalog_investigations', '—')} |
| Tools Built | {activity.get('tools_built', '—')} |

---

{narrative}

---

{ic.format_search_section("Web Signals — Virtuals / ACP", search)}

---

## Sources
- CoinGecko + DefiLlama (`get_virtuals_snapshot`) — keyless, real-time
- `data/reputation.json` — this repo's own published, git-derived activity ledger
- Live web search ({search.get('provider') or 'unavailable'})
- LLM synthesis: {provider or 'unavailable this cycle'}

---

*Report generated by `agents/virtuals_sweep.py` — revived {datetime.now(timezone.utc).strftime('%Y-%m-%d')} after the
original ad hoc sweep silently stopped; see intel/reports/virtuals-2026-07-01-20.md for the last
pre-revival report.*
"""
    path = ic.write_report("virtuals", body)
    summary = f"Virtuals sweep: health {score}/10, VIRTUAL ${snapshot.get('virtual_price_usd', '—')} ({snapshot.get('virtual_change_24h_pct', '—')}% 24h)."
    ic.log_sweep_memory("agents/virtuals_sweep.py", str(score), summary, path, tags=["virtuals"])
    print(f"[virtuals_sweep] health={score} — wrote {os.path.relpath(path, ic.ROOT)}")
    return {"score": score, "path": path}


if __name__ == "__main__":
    run()
