"""
VAPE Virtuals Protocol & ACP Sweep — revives the "Virtuals Protocol & ACP
Sweep Report" cron (see intel/reports/virtuals-*.md). Same story as
security_sweep.py's docstring.

Real data: agents/data_fetchers.get_virtuals_snapshot() (VIRTUAL price/mcap/
volume + protocol TVL, keyless CoinGecko+DefiLlama) for the ecosystem side,
and data/reputation.json (this repo's own real, published activity ledger —
generated by agents/publish_reputation.py from actual git/ACP history) for
VAPE's own agent status, instead of re-deriving it from a live ACP CLI call
each cycle. PROTOCOL HEALTH is computed deterministically from the real
VIRTUAL price trend. One bounded web search adds ecosystem news.

Usage: python agents/virtuals_sweep.py
"""
import json
import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from agents.data_fetchers import get_virtuals_snapshot  # noqa: E402
from agents import intel_common as ic  # noqa: E402
from agents import research_engine  # noqa: E402

REPUTATION_PATH = os.path.join(ic.ROOT, "data", "reputation.json")


def load_reputation():
    try:
        with open(REPUTATION_PATH) as f:
            return json.load(f)
    except Exception:
        return {}


def compute_health_score(snapshot):
    """0-10, starts neutral at 5. Four independent real factors drive the
    swing — see intel_common.py's module docstring for why this isn't
    LLM-guessed. A single day's price change is noisy (any token can swing
    double digits on thin volume in a day) and was previously the ONLY
    input; this weights it down and adds three sturdier signals so one bad
    (or good) day can't single-handedly swing the whole score:

    - 24h price change (small weight — noisy, kept for immediacy)
    - 7d price trend (medium weight — smooths single-day noise)
    - 7d protocol TVL trend (medium weight — real capital staying in the
      ecosystem is harder to fake than a price pump, and moves independently
      of the token's own price action)
    - volume/mcap ratio (small weight — a token trading at a healthy
      fraction of its market cap daily has real, active markets; one barely
      trading at all is illiquid regardless of what price is doing)

    Any factor whose real data is unavailable this cycle is simply skipped
    (not defaulted to neutral/zero), so a single flaky upstream API degrades
    the score's precision, never its direction."""
    score = 5.0
    chg_24h = snapshot.get("virtual_change_24h_pct")
    if isinstance(chg_24h, (int, float)):
        if chg_24h >= 5:
            score += 1
        elif chg_24h > 0:
            score += 0.5
        elif chg_24h <= -10:
            score -= 1
        elif chg_24h < 0:
            score -= 0.5

    chg_7d = snapshot.get("virtual_change_7d_pct")
    if isinstance(chg_7d, (int, float)):
        if chg_7d >= 10:
            score += 2
        elif chg_7d > 0:
            score += 1
        elif chg_7d <= -20:
            score -= 2
        elif chg_7d < 0:
            score -= 1

    tvl_7d = snapshot.get("tvl_change_7d_pct")
    if isinstance(tvl_7d, (int, float)):
        if tvl_7d >= 10:
            score += 2
        elif tvl_7d > 0:
            score += 1
        elif tvl_7d <= -20:
            score -= 2
        elif tvl_7d < 0:
            score -= 1

    vol_ratio = snapshot.get("volume_to_mcap_pct")
    if isinstance(vol_ratio, (int, float)):
        if vol_ratio >= 5:
            score += 1
        elif vol_ratio < 0.5:
            score -= 1

    return max(0, min(10, round(score, 1)))


def run():
    snapshot = get_virtuals_snapshot()
    rep = load_reputation()
    score = compute_health_score(snapshot)

    identity = rep.get("identity", {})
    activity = rep.get("verifiable_activity", {})
    offerings = rep.get("capabilities", {}).get("offerings", [])
    live_offerings = [o for o in offerings if o.get("auto") or o.get("x402")]

    search = ic.web_search_snippets("Virtuals Protocol ACP agent commerce news update", max_results=8)

    grounding = (
        f"PROTOCOL HEALTH (already computed from 4 weighted real factors below, do not change it): {score}/10\n"
        f"VIRTUAL price: ${snapshot.get('virtual_price_usd', 'unavailable')} "
        f"({snapshot.get('virtual_change_24h_pct', 'unavailable')}% 24h, "
        f"{snapshot.get('virtual_change_7d_pct', 'unavailable')}% 7d, "
        f"{snapshot.get('virtual_change_30d_pct', 'unavailable')}% 30d)\n"
        f"VIRTUAL market cap: ${snapshot.get('virtual_mcap_usd', 'unavailable')}\n"
        f"VIRTUAL 24h volume / market cap: {snapshot.get('volume_to_mcap_pct', 'unavailable')}% "
        f"(liquidity/activity signal — a healthy token typically trades a few percent of its mcap daily)\n"
        f"Virtuals Protocol TVL: ${snapshot.get('protocol_tvl_usd', 'unavailable')} "
        f"({snapshot.get('tvl_change_7d_pct', 'unavailable')}% 7d, {snapshot.get('tvl_change_30d_pct', 'unavailable')}% 30d)\n"
        f"VAPE's own real activity: {json.dumps(activity)}\n"
        f"VAPE's live offerings: {len(live_offerings)} of {len(offerings)} total\n\n"
        f"Web search on Virtuals/ACP news:\n"
        f"{[r['title'] + ': ' + r['snippet'] for r in search.get('results', [])] or 'none available'}"
    )
    synth = research_engine.synthesize(
        {"topic": "Virtuals Protocol ecosystem", "task_type": "market_intel",
         "known_facts": {}, "findings": [], "deep_extracts": [], "raw_user_block": grounding, "log": {}},
        role="autonomous agent reporting on the Virtuals Protocol ecosystem it operates in",
        extra_instructions=(
            "Never invent ecosystem stats, agent counts, or news beyond what's given. Write two "
            "sections in markdown, each starting with '### ':\n"
            "1. Ecosystem & ACP Activity — what the price/TVL trends, liquidity signal, and search "
            "results say about protocol health right now, at whatever depth they support. Explain "
            "which of the four factors is driving the score this cycle, not just the score itself.\n"
            "2. Action Items for VAPE — bullets grounded in VAPE's own real activity numbers above, "
            "as many as are genuinely warranted (not a fixed count)."
        ),
        trailers=[], max_tokens=2200, temperature=0.5,
    )
    narrative = ic.safe_narrative(synth["narrative"])
    provider = synth["provider"]

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    body = f"""# Virtuals Protocol & ACP Sweep Report

**Date:** {stamp}
**Agent:** VAPE (token `{identity.get('vape_token', 'unknown')}`, Base chain 8453)

---

## PROTOCOL HEALTH: {score}/10

Computed deterministically from four weighted real factors: 24h price change ({snapshot.get('virtual_change_24h_pct', '—')}%,
small weight — noisy), 7d price trend ({snapshot.get('virtual_change_7d_pct', '—')}%, medium weight), 7d Protocol TVL
trend ({snapshot.get('tvl_change_7d_pct', '—')}%, medium weight — real capital staying in the ecosystem), and
24h volume/market-cap ratio ({snapshot.get('volume_to_mcap_pct', '—')}%, small weight — liquidity/activity signal).
A single day's price move can no longer single-handedly swing this score.

---

## Token Movement — VIRTUAL (real, CoinGecko + DefiLlama)

| Metric | Value |
|---|---|
| Price | {ic.fmt_price(snapshot.get('virtual_price_usd'))} |
| 24h Change | {snapshot.get('virtual_change_24h_pct') if snapshot.get('virtual_change_24h_pct') is not None else 'unavailable'}% |
| 7d Change | {snapshot.get('virtual_change_7d_pct') if snapshot.get('virtual_change_7d_pct') is not None else 'unavailable'}% |
| 30d Change | {snapshot.get('virtual_change_30d_pct') if snapshot.get('virtual_change_30d_pct') is not None else 'unavailable'}% |
| Market Cap | {ic.fmt_usd(snapshot.get('virtual_mcap_usd'))} |
| 24h Volume | {ic.fmt_usd(snapshot.get('virtual_vol_24h_usd'))} |
| Volume / Market Cap | {snapshot.get('volume_to_mcap_pct') if snapshot.get('volume_to_mcap_pct') is not None else 'unavailable'}% |
| Protocol TVL | {ic.fmt_usd(snapshot.get('protocol_tvl_usd'))} |
| TVL 7d Change | {snapshot.get('tvl_change_7d_pct') if snapshot.get('tvl_change_7d_pct') is not None else 'unavailable'}% |
| TVL 30d Change | {snapshot.get('tvl_change_30d_pct') if snapshot.get('tvl_change_30d_pct') is not None else 'unavailable'}% |

---

## VAPE's Own ACP Status (real, from `data/reputation.json`)

| Field | Value |
|---|---|
| Agent | {identity.get('name', 'VAPE')} |
| Wallet | {identity.get('wallet', '—')} |
| ERC-8004 ID | {identity.get('erc8004_id', '—')} |
| Live Offerings | {len(live_offerings)} of {len(offerings)} |
| Reports Published | {activity.get('reports_published', '—')} |
| Intel Reports | {activity.get('intel_reports', '—')} |
| Catalog Investigations | {activity.get('catalog_investigations', '—')} |
| Tools Built | {activity.get('tools_built', '—')} |

---

{narrative}

---

{ic.format_search_section("Web Signals — Virtuals / ACP", search)}

---

## Sources
- CoinGecko + DefiLlama (`get_virtuals_snapshot`) — keyless, real-time
- `data/reputation.json` — this repo's own published, git-derived activity ledger
- Live web search ({search.get('provider') or 'unavailable'})
- Narrative synthesis: {'VAPE' if provider else 'unavailable this cycle'}

---

*Report generated by `agents/virtuals_sweep.py` — revived {datetime.now(timezone.utc).strftime('%Y-%m-%d')} after the
original ad hoc sweep silently stopped; see intel/reports/virtuals-2026-07-01-20.md for the last
pre-revival report.*
"""
    path = ic.write_report("virtuals", body)
    summary = f"Virtuals sweep: health {score}/10, VIRTUAL ${snapshot.get('virtual_price_usd', '—')} ({snapshot.get('virtual_change_24h_pct', '—')}% 24h)."
    ic.log_sweep_memory("agents/virtuals_sweep.py", str(score), summary, path, tags=["virtuals"])
    print(f"[virtuals_sweep] health={score} — wrote {os.path.relpath(path, ic.ROOT)}")
    return {"score": score, "path": path}


if __name__ == "__main__":
    run()
