"""
VAPE Central Memory System — General-Purpose Brain (Priority 1)

The Memory Retriever is the shared long-term intelligence layer for the entire V.A.P.E. system:
- Detective flows (agents/run.py, agents/vape.py) query Memory for past findings, lessons, patterns
- Builder (agents/builder.py) grounds all code generation in Memory + auto-appends outputs
- Social tools (future X/MCP wrappers) store social findings, sentiment shifts, narrative events
- Self-improvement flows (agents/self_improve.py) record lessons learned
- Any component can search or append — creating a compounding intelligence loop

Design principles:
- Append-only: findings, lessons, skills are immutable once added (integrity)
- Searchable: simple relevance scoring, category filtering, time-range queries
- Secure: sanitized inputs, no PII/secrets, full operation logging
- Efficient: JSON/JSONL format, no database overhead, file-based on disk
- Metadata-rich: timestamps, sources, confidence scores, interconnection pointers

Storage:
  skillforge/memory/
    ├── tools-registry.json        # [tool] definitions + tiers (static/fuzzing/ai-redteam/recon)
    ├── findings.jsonl             # [finding] security discoveries, anomalies, patterns
    ├── lessons.jsonl              # [lesson] successful patterns, failures, best practices
    ├── skills.jsonl               # [skill] playbooks generated by Builder
    ├── social-events.jsonl        # [event] X sentiment, narrative shifts, social threats
    └── INDEX.md                   # Human-readable index + usage guide
"""

import json
import time
from datetime import datetime, timedelta
from pathlib import Path
from typing import List, Dict, Any, Optional
import hashlib
import re
import logging

# ============================================================================
# Configuration & Logging
# ============================================================================

MEMORY_DIR = Path(__file__).parent
FINDINGS_FILE = MEMORY_DIR / "findings.jsonl"
LESSONS_FILE = MEMORY_DIR / "lessons.jsonl"
SKILLS_FILE = MEMORY_DIR / "skills.jsonl"
SOCIAL_EVENTS_FILE = MEMORY_DIR / "social-events.jsonl"
TOOLS_REGISTRY = MEMORY_DIR / "tools-registry.json"
INDEX_FILE = MEMORY_DIR / "INDEX.md"

# Ensure directory exists
MEMORY_DIR.mkdir(parents=True, exist_ok=True)

# Logger
logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] [MEMORY] %(levelname)s: %(message)s"
)
logger = logging.getLogger("VAPE.Memory")


# ============================================================================
# Data Validation & Sanitization
# ============================================================================

def sanitize_input(text: str, max_len: int = 5000) -> str:
    """Sanitize user input: remove secrets, limit length, strip dangerous chars."""
    if not isinstance(text, str):
        return ""
    # Remove common secret patterns (API keys, addresses, PII)
    text = re.sub(r'(sk_|pk_|api_key|secret|password|token).*?[\s\n]', '', text, flags=re.IGNORECASE)
    text = re.sub(r'0x[a-fA-F0-9]{40,}', '[ADDRESS]', text)  # Ethereum addresses (partial mask)
    text = text[:max_len].strip()
    return text


def validate_category(category: str) -> bool:
    """Validate that category is one of the allowed types."""
    allowed = {"finding", "lesson", "skill", "social_event", "tool"}
    return category in allowed


# ============================================================================
# Core Memory Operations
# ============================================================================

class MemoryEntry:
    """Base entry in Memory — each is immutable once written."""
    
    def __init__(
        self,
        category: str,
        title: str,
        content: str,
        source: str = "system",
        tags: Optional[List[str]] = None,
        confidence: float = 0.8,
        metadata: Optional[Dict[str, Any]] = None
    ):
        self.id = hashlib.sha256(f"{title}{time.time()}".encode()).hexdigest()[:12]
        self.category = category
        self.title = sanitize_input(title, 200)
        self.content = sanitize_input(content)
        self.source = sanitize_input(source, 100)
        self.tags = tags or []
        self.confidence = max(0, min(1, confidence))  # Clamp to [0, 1]
        self.timestamp = datetime.utcnow().isoformat()
        self.metadata = metadata or {}
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "category": self.category,
            "title": self.title,
            "content": self.content,
            "source": self.source,
            "tags": self.tags,
            "confidence": self.confidence,
            "timestamp": self.timestamp,
            "metadata": self.metadata,
        }


def append_to_memory(
    category: str,
    title: str,
    content: str,
    source: str = "system",
    tags: Optional[List[str]] = None,
    confidence: float = 0.8,
    metadata: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Append a new entry to Memory. Returns the entry dict with assigned ID.
    
    Args:
        category: "finding", "lesson", "skill", "social_event", or "tool"
        title: Short description (<=200 chars)
        content: Full content (sanitized)
        source: Where this came from (e.g. "agents/run.py", "X-monitor", "builder")
        tags: List of searchable tags
        confidence: Confidence score 0–1 (for findings/lessons)
        metadata: Extra data (dict)
    
    Returns:
        The appended entry as dict with assigned ID and timestamp.
    """
    if not validate_category(category):
        logger.error(f"Invalid category: {category}")
        return {}
    
    try:
        entry = MemoryEntry(category, title, content, source, tags, confidence, metadata)
        entry_dict = entry.to_dict()
        
        # Choose target file by category
        target_file = {
            "finding": FINDINGS_FILE,
            "lesson": LESSONS_FILE,
            "skill": SKILLS_FILE,
            "social_event": SOCIAL_EVENTS_FILE,
        }.get(category)
        
        if target_file:
            with open(target_file, "a") as f:
                f.write(json.dumps(entry_dict) + "\n")
            logger.info(f"Appended {category} '{entry.title}' (ID: {entry.id})")
        
        return entry_dict
    except Exception as e:
        logger.error(f"Failed to append to memory: {e}")
        return {}


# ============================================================================
# Backward-compatible loading
# ============================================================================
#
# Older SKILLFORGE workflows (harvest.py, toolcheck.py, intel-cycle) write
# entries in a legacy schema:
#   findings.jsonl:  {ts, source, severity, target, summary, ref}
#   lessons.jsonl:   {ts, action, outcome, bounty_usd, note}
# The new brain uses {id, category, title, content, source, tags, confidence,
# timestamp, metadata}. We normalize legacy rows on read so the entire memory
# corpus is queryable without rewriting history or breaking the live workflows.

_MEMORY_FILES = {
    "finding": FINDINGS_FILE,
    "lesson": LESSONS_FILE,
    "skill": SKILLS_FILE,
    "social_event": SOCIAL_EVENTS_FILE,
}


def _normalize_entry(entry: Dict[str, Any], default_category: str) -> Dict[str, Any]:
    """Coerce a raw row (new or legacy schema) into the canonical entry shape."""
    # Already new schema
    if "category" in entry and ("title" in entry or "content" in entry):
        entry.setdefault("timestamp", entry.get("ts", ""))
        entry.setdefault("confidence", 0.7)
        entry.setdefault("tags", [])
        entry.setdefault("source", "unknown")
        return entry

    # Legacy finding: {ts, source, severity, target, summary, ref}
    if "summary" in entry:
        sev = str(entry.get("severity", "INFO")).upper()
        conf = {"CRITICAL": 0.95, "HIGH": 0.9, "MEDIUM": 0.8,
                "LOW": 0.6, "INFO": 0.6}.get(sev, 0.6)
        return {
            "id": entry.get("ref", ""),
            "category": default_category,
            "title": f"{entry.get('target', 'repo')}: {entry.get('summary', '')[:120]}",
            "content": entry.get("summary", ""),
            "source": entry.get("source", "unknown"),
            "tags": [t for t in [entry.get("target"), sev.lower()] if t],
            "confidence": conf,
            "timestamp": entry.get("ts", ""),
            "metadata": {"severity": sev, "ref": entry.get("ref", "")},
        }

    # Legacy lesson: {ts, action, outcome, bounty_usd, note}
    if "action" in entry or "outcome" in entry:
        return {
            "id": "",
            "category": default_category,
            "title": f"{entry.get('action', 'lesson')}: {entry.get('outcome', '')[:120]}",
            "content": entry.get("note", entry.get("outcome", "")),
            "source": entry.get("source", "skillforge"),
            "tags": [t for t in [entry.get("action")] if t],
            "confidence": 0.7,
            "timestamp": entry.get("ts", ""),
            "metadata": {"bounty_usd": entry.get("bounty_usd", 0)},
        }

    # Unknown shape: best-effort passthrough
    entry.setdefault("category", default_category)
    entry.setdefault("title", str(entry)[:120])
    entry.setdefault("content", json.dumps(entry)[:500])
    entry.setdefault("source", "unknown")
    entry.setdefault("tags", [])
    entry.setdefault("confidence", 0.5)
    entry.setdefault("timestamp", entry.get("ts", ""))
    return entry


def _load_all_entries() -> List[Dict[str, Any]]:
    """Load and normalize every entry across all memory files."""
    all_entries: List[Dict[str, Any]] = []
    for cat, file in _MEMORY_FILES.items():
        if file.exists():
            try:
                with open(file, "r") as f:
                    for line in f:
                        if line.strip():
                            try:
                                raw = json.loads(line)
                            except json.JSONDecodeError:
                                continue
                            all_entries.append(_normalize_entry(raw, cat))
            except Exception as e:
                logger.error(f"Error reading {file}: {e}")
    return all_entries


def search_memory(
    query: str,
    category: Optional[str] = None,
    tags: Optional[List[str]] = None,
    max_results: int = 10,
    min_confidence: float = 0.0,
    days_back: Optional[int] = None
) -> List[Dict[str, Any]]:
    """
    Search Memory using keyword matching + optional filters.
    
    Args:
        query: Search text (keyword)
        category: Filter by category (e.g. "finding", "lesson", "skill")
        tags: Filter to entries with any of these tags
        max_results: Max entries to return
        min_confidence: Only return entries with confidence >= this
        days_back: Only return entries from the last N days
    
    Returns:
        List of matching entries, ranked by relevance (keyword matches, recency, confidence).
    """
    query_lower = query.lower()
    results = []
    cutoff_time = None
    
    if days_back:
        cutoff_time = (datetime.utcnow() - timedelta(days=days_back)).isoformat()
    
    # Merge all files and search (normalized: new + legacy schema)
    all_entries = _load_all_entries()
    
    # Filter and rank
    for entry in all_entries:
        # Category filter
        if category and entry.get("category") != category:
            continue
        
        # Time filter
        if cutoff_time and entry.get("timestamp", "") < cutoff_time:
            continue
        
        # Confidence filter
        if entry.get("confidence", 0) < min_confidence:
            continue
        
        # Tag filter
        if tags and not any(tag in entry.get("tags", []) for tag in tags):
            continue
        
        # Keyword matching: score based on matches in title + content
        title = entry.get("title", "").lower()
        content = entry.get("content", "").lower()
        matches = title.count(query_lower) + content.count(query_lower)
        
        if matches > 0:
            entry["_relevance_score"] = matches + entry.get("confidence", 0.5)
            results.append(entry)
    
    # Sort by relevance (highest first)
    results.sort(key=lambda x: x["_relevance_score"], reverse=True)
    results = results[:max_results]
    
    # Remove internal scoring field
    for r in results:
        r.pop("_relevance_score", None)
    
    logger.info(f"Search query '{query}' returned {len(results)} results")
    return results


def get_memory_stats() -> Dict[str, Any]:
    """Get summary statistics about current Memory state."""
    stats = {
        "timestamp": datetime.utcnow().isoformat(),
        "total_entries": 0,
        "by_category": {},
        "by_source": {},
        "confidence_distribution": {"high": 0, "medium": 0, "low": 0}
    }
    
    all_entries = _load_all_entries()
    
    stats["total_entries"] = len(all_entries)
    
    for entry in all_entries:
        cat = entry.get("category", "unknown")
        src = entry.get("source", "unknown")
        conf = entry.get("confidence", 0.5)
        
        stats["by_category"][cat] = stats["by_category"].get(cat, 0) + 1
        stats["by_source"][src] = stats["by_source"].get(src, 0) + 1
        
        if conf >= 0.8:
            stats["confidence_distribution"]["high"] += 1
        elif conf >= 0.5:
            stats["confidence_distribution"]["medium"] += 1
        else:
            stats["confidence_distribution"]["low"] += 1
    
    logger.info(f"Memory stats: {stats['total_entries']} total entries")
    return stats


# ============================================================================
# Tools Registry (static registry for SKILLFORGE tools)
# ============================================================================

def init_tools_registry():
    """Initialize or load tools registry."""
    default_registry = {
        "static_analysis": [
            {"name": "slither", "version": "0.10+", "tier": "static", "enabled": True},
            {"name": "aderyn", "version": "0.3+", "tier": "static", "enabled": True},
            {"name": "mythril", "version": "0.24+", "tier": "static", "enabled": True},
        ],
        "fuzzing": [
            {"name": "echidna", "version": "2.0+", "tier": "fuzzing", "enabled": True},
            {"name": "foundry", "version": "0.2+", "tier": "fuzzing", "enabled": True},
        ],
        "ai_redteam": [
            {"name": "garak", "version": "0.5+", "tier": "ai-redteam", "enabled": True},
            {"name": "promptfoo", "version": "0.5+", "tier": "ai-redteam", "enabled": True},
        ],
        "recon": [
            {"name": "token_safety", "version": "1.0", "tier": "recon", "enabled": True},
            {"name": "contract_recon", "version": "1.0", "tier": "recon", "enabled": True},
            {"name": "base_rpc_analyzer", "version": "1.0", "tier": "recon", "enabled": True},
        ]
    }
    
    if not TOOLS_REGISTRY.exists():
        with open(TOOLS_REGISTRY, "w") as f:
            json.dump(default_registry, f, indent=2)
        logger.info("Initialized tools registry")
    
    return default_registry


def get_tools_registry() -> Dict[str, Any]:
    """Load tools registry."""
    if TOOLS_REGISTRY.exists():
        try:
            with open(TOOLS_REGISTRY, "r") as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Error loading tools registry: {e}")
    return init_tools_registry()


# ============================================================================
# INDEX Generation (human-readable summary)
# ============================================================================

def generate_index():
    """Generate a human-readable INDEX.md for Memory."""
    stats = get_memory_stats()
    
    header = (
        "# VAPE Central Memory Index\n\n"
        f"**Last updated:** {stats['timestamp']}\n\n"
        "## Overview\n\n"
        "The Central Memory is the shared intelligence brain for V.A.P.E. All components "
        "(Detective, Builder, Social tools, Self-improvement) query and append to Memory, "
        "creating a compounding intelligence loop.\n\n"
        "## Statistics\n\n"
        f"- **Total entries:** {stats['total_entries']}\n"
        f"- **By category:** {stats['by_category']}\n"
        f"- **By source:** {stats['by_source']}\n"
        f"- **Confidence distribution:** {stats['confidence_distribution']}\n"
    )

    body = r"""
## Usage

### Append a Finding (Security discovery, anomaly, pattern)

```python
from skillforge.memory.retriever import append_to_memory

append_to_memory(
    category="finding",
    title="High TVL outflow from Lido on Base",
    content="$2.5M TVL left Lido/Base between 14:00-14:30 UTC. Possible hedge or exploit fear.",
    source="agents/run.py",
    tags=["base", "tvl", "lido", "anomaly"],
    confidence=0.9,
    metadata={"chain": "base", "protocol": "lido", "amount_usd": 2500000}
)
```

### Append a Lesson (Pattern, best practice, or failure)

```python
append_to_memory(
    category="lesson",
    title="Static analysis + LLM grounding improves exploit detection",
    content="Running slither + Groq analysis together catches 40% more zero-days than either alone.",
    source="agents/run.py",
    tags=["pattern", "slither", "llm", "detection"],
    confidence=0.85
)
```

### Append a Skill (Playbook generated by Builder)

```python
append_to_memory(
    category="skill",
    title="sc-static-analysis playbook v2",
    content="[Full code or high-level recipe for running static analysis across Solidity repos]",
    source="agents/builder.py",
    tags=["builder", "playbook", "static-analysis"],
    confidence=0.8
)
```

### Search Memory

```python
from skillforge.memory.retriever import search_memory

# Search for recent high-confidence findings about Base anomalies
findings = search_memory(
    query="base tvl anomaly",
    category="finding",
    min_confidence=0.8,
    days_back=7
)

# Search for lessons about detection patterns
lessons = search_memory(
    query="exploit detection pattern",
    category="lesson",
    tags=["pattern"]
)
```

### Get Memory Stats

```python
from skillforge.memory.retriever import get_memory_stats

stats = get_memory_stats()
print(f"Total memory entries: {stats['total_entries']}")
```

## Files

- `findings.jsonl` — Security discoveries, anomalies, patterns from Detective runs
- `lessons.jsonl` — Best practices, successful patterns, failure modes
- `skills.jsonl` — Playbooks and skill definitions generated by Builder
- `social-events.jsonl` — X/social sentiment shifts, narrative events, social threats
- `tools-registry.json` — Static registry of available security tools
- `INDEX.md` — This file

## Integration Points

- **agents/run.py** — searches Memory for past findings before analysis, appends new discoveries
- **agents/builder.py** — grounds code generation in Memory lessons, auto-appends generated skills
- **agents/self_improve.py** — records lessons and improvements to Memory
- **Future X/MCP tools** — append social events and sentiment to Memory
- **SKILLFORGE synthesis** — uses Memory as source of truth for tool/skill generation

## Security

- All inputs are sanitized: secrets, PII, and dangerous chars removed
- Entries are append-only: no deletion or modification after creation
- Full operation logging: every read/write is logged
- No unstructured storage: all entries have category, timestamp, source, confidence

---

*Memory is the backbone of V.A.P.E.'s compounding intelligence. Every successful pattern, every threat discovered, every lesson learned, is permanently recorded and available to all future runs.*
"""

    index_md = header + body
    with open(INDEX_FILE, "w") as f:
        f.write(index_md)
    logger.info("Generated INDEX.md")


# ============================================================================
# Initialization
# ============================================================================

def init_memory():
    """One-time initialization of all Memory files."""
    init_tools_registry()
    generate_index()
    logger.info("Memory system initialized")


if __name__ == "__main__":
    # Test the memory system
    init_memory()
    
    # Append a test finding
    result = append_to_memory(
        category="finding",
        title="Test finding - high TVL anomaly detected",
        content="Sample finding for testing the memory retrieval system.",
        source="test",
        tags=["test", "anomaly"],
        confidence=0.85
    )
    print(f"Appended entry: {result}")
    
    # Search
    results = search_memory("anomaly", category="finding")
    print(f"Search results: {len(results)} found")
    for r in results:
        print(f"  - {r['title']} (confidence: {r['confidence']})")
    
    # Stats
    stats = get_memory_stats()
    print(f"Memory stats: {stats}")
